apiVersion: v1
kind: pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    startupProbe:
      httpGet:
        path: /dkchdsjksah
        port: 80
    periodSeconds: 1
    failureThreshold: 4