apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: nginx
    name: nginx-container
    startupProbe:
      httpGet:
        path: /dkchdsjksah
        port: 80
    periodSeconds: 1
    failureThreshold: 4