apiVersion: v1
kind: Pod
metadata:
  name: pod-mongo
spec:
  containers:
  - image: mongodb
    name: mongo-container
    startupProbe:
      tcpSocket:
        port: 2719 #default 2717
        port: 80
      periodSeconds: 1
      failureThreshold: 5