apiVersion: v1
kind: Pod
metadata:
  name: pod-mongo
spec:
  containers:
  - image: mongodb
    name: mongo-container
    startupProbe:
      tcpSocket:
        port: 27019 #default 27017
        port: 80
      periodSeconds: 1
      failureThreshold: 5

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
  - image: nginx
    name: nginx-container
    startupProbe:
      exec:
        command:
        - "cat"
        - "/usr/share/nginx/html/index.html"
      periodSeconds: 1
      failureThreshold: 3